a, b, operation = float(input()), float(input()), input()
if operation == '+': print(a + b)
elif operation == '-': print(a - b)
elif (operation == '/') and (a and b != 0): print(a / b)
elif operation == '*': print(a * b)
elif operation == 'mod' and (a and b != 0): print(a % b)
elif operation == 'pow': print(a ** b)
elif operation == 'div' and (a and b != 0): print(a // b)
else: print('Деление на 0!')